apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
  - name: Researchly PostgreSQL
    type: grafana-postgresql-datasource
    uid: postrec-postgres
    access: proxy
    url: postgres:5432
    user: postrec
    database: postrec
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: postrec
